spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    baseline-on-migrate: true

logging:
  level:
    com.fitcrm.user: INFO
    org.springframework: WARN