name: Build, Test & Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Run Tests
        run: ./mvnw clean verify

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: fitcrm-user-service-jar
          path: target/fitcrm-user-service-0.0.1-SNAPSHOT.jar
          retention-days: 1

  flyway-check:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: fitcrm_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clean, migrate and validate Flyway
        run: |
          ./mvnw --batch-mode flyway:clean flyway:migrate \
            -Dflyway.url=jdbc:postgresql://localhost:5432/fitcrm_test \
            -Dflyway.user=test \
            -Dflyway.password=test \
            -Dflyway.locations=classpath:db/migration \
            -Dflyway.cleanDisabled=false

          ./mvnw --batch-mode flyway:validate \
            -Dflyway.url=jdbc:postgresql://localhost:5432/fitcrm_test \
            -Dflyway.user=test \
            -Dflyway.password=test \
            -Dflyway.locations=classpath:db/migration
  docker:
    needs: [build-and-test, flyway-check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: fitcrm-user-service-jar
          path: .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fitcrm-user-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fitcrm-user-service:${{ github.sha }}